### ISSUE TITLE
Protobuf compatibility could be relaxed

### ISSUE THREAD

**Issue by plule-ansys** [ansys/ansys-api-template#10]
I am currently using this template to try to make `ansys-platform-instancemanagement` (PyPIM) compatible with Python's protobuf 4, and it looks like the dependency statement toward protobuf is currently more restrictive than it should be, as the generated code is compatible with protobuf >4 out of the box. The code is currently generated with `protoc` 3.19, making it compatible with the `protobuf` package 4.x

`protobuf~=3.19` could instead be `protobuf>=3.19,<5`.

I did an end to end test by regenerating PyPIM API package (`ansys-api-platform-instancemanagement`) with this template and using it with PyDPF and protobuf 4.22.3 with no issue.

**Comment by greschd** [comment]
Thanks @plule-ansys, I think that just got missing. See also https://github.com/ansys/ansys-tools-protoc-helper#upgrade-plans for compatibility charts.

**Comment by plule-ansys** [comment]
Oh I did not see that you had an upgrade plan in place already. Here is an article detailing that the code generated with `protoc` 3.19 is actually compatible with the package `protobuf 4.21` and following: https://protobuf.dev/news/2022-05-06/#python-updates

It could mean that protobuf 4 is actually compatible with many pyansys libs

**Comment by greschd** [comment]
Yes, I think that's what this means. This was the reason for switching to `3.19` in the `0.4` release, but we missed it in the template.
