### ISSUE TITLE
Cookiecutter template subtitutions not applied in ci.yml

### ISSUE THREAD

**Issue by iboyd-ansys** [ansys/ansys-api-template#9]
I just created a new API repo for SystemCoupling using the template and following instructions. On the whole this worked smoothly, but the raw cookiecutter template fields remained in the `ci.yml` file.

i.e. the "Test import" section still contained these lines:

```
          python -c "import {{ cookiecutter._dot_package_name_no_ver }}.v{{ cookiecutter.api_version }}; print('Sucessfully imported {{ cookiecutter._dot_package_name_no_ver }}.v{{ cookiecutter.api_version }}')"
          python -c "from {{ cookiecutter._dot_package_name_no_ver }}.v{{ cookiecutter.api_version }} import __version__; print(__version__)"
```

**Comment by greschd** [comment]
Thanks for reporting @iboyd-ansys, I can reproduce this issue on my side.
